#include "crc32.h"

const struct crc32_state crc32_init;

/* lookup table for IEEE polynomial generated by mkcrc32tab.c */
static const uint32_t crc32const[256] =
#include "crc32tab.h"

static uint32_t consume(uint32_t crc, const uint8_t *p, size_t len) {
	size_t i;

	crc = ~crc;
	for (i = 0; i < len; i++) crc = crc32const[crc&0xff^p[i]] ^ crc>>8;

	return ~crc;
}

extern void crc32_block(union digest_state *u, const uint8_t *p) {
	*(uint32_t*)u = consume(*(uint32_t*)u, p, CRC32_BLOCKLEN);
}

extern void crc32_final(union digest_state *u, uint8_t *p, size_t len, uint8_t *d) {
	uint32_t h = consume(*(uint32_t*)u, p, len);

	/* write result in big endian */
	d[0] = h >> 24;
	d[1] = h >> 16;
	d[2] = h >> 8;
	d[3] = h >> 0;
}
