.TH DIGEST 1 2014-03-14 "digest" "User Commands"
.SH NAME
digest \- Calculate various message digests

.SH SYNOPSIS
\fBdigest \fR[ \fB-a\fIalgorithm \fR| \fB-r \fR| \fB-s \fR] [ \fB-f\fIformat \fR]
.RB [ - ]
.IR file ...

\fIdigest\fBsum [ \fB-f\fIformat \fR]
.RB [ - ]
.IR file ...

.B digest
.B -h

.SH DESCRIPTION
\fBdigest\fR computes message digests of the supplied files. Different kinds of
message digests are available and can be selected with the
.BI -a algorithm
option. Typically \fBdigest\fR is installed as \fBmd5sum\fR, \fBsha1sum\fR, etc.
In this case, \fBdigest\fR automatically detects the digest to compute. Calling
\fBdigest\fR with no arguments, or with \fB-h\fR gives a brief reminder of
\fBdigest\fR's options and a list of supported digests.

The following message digest and checksum algorithms are supported if enabled
at compile time: Adler-32, BSD style checksum, POSIX \fBcksum\fR(1), CRC-32
(IEEE polynomial), MD5, SHA-1, SHA-224, SHA-256, System V style checksum.

.SH OPTIONS
.IP \fB-a\fIalgorithm
Select a message digest algorithm. This flag is only neccessary if the algorithm
cannot be deducted from the program name. Possible values for \fIalgorithm\fR
are \fBadler32\fR, \fBbsd\fR, \fBcksum\fR, \fBcrc32\fR, \fBmd5\fR, \fBsha1\fR,
\fBsha224\fR, \fBsha256\fR and \fBsysv\fR.

.IP \fB-f\fIformat
Select an output format. Most algorithms default to the \fBx\fR output format,
for all other algorithms their output format is noted. All digest formats marked
with (\fIn\fR) are not available for digests longer than \fIn\fR bits. The
following values are possible for \fIformat\fR:

.RS
.IP \fBb
Used BSD format as used by
.BR sum (1).
Default for the \fBbsd\fR digest. (16)

.IP \fBc
Use \fBcksum\fR format, as defined in POSIX.1 2008. (16, 32)

.IP \fBs
Use System V format, as used by
.BR sum (1).
Default for the \fBsysv\fR digest. (16)

.IP \fBx
Show checksum in hexadecimal followed by two spaces, followed by a filename.

.IP \fBy
Show checksum in hexadecimal followed by length followed by filename.

.RE

.IP \fB-h
Print a brief reminder of \fBdigest\fR's command line syntax and a list of
available message digest algorithms.

.IP \fB-r
Equivalent to \fB-absd\fR for compatibility with GNU
.BR sum (1).

.IP \fB-s
Equivalent to \fB-asysv\fR for compatibility with GNU
.BR sum (1).

.SH AUTHOR
Written by Robert Clausecker <fuzxxl@gmail.com>.

.SH SEE ALSO
.BR sum (1),
.BR cksum (1)









