#include <limits.h>
#include <string.h>
#include "finalize.h"
#include "md5.h"

const struct md5_state md5_init =
	{ 0, { 0x67452301, 0xefcdab89, 0x98badcfe, 0x10325476 } };

/* shift parameters */
static const char shiftp[64] = {
	7, 12, 17, 22, 7, 12, 17, 22, 7, 12, 17, 22, 7, 12, 17, 22,
	5,  9, 14, 20, 5,  9, 14, 20, 5,  9, 14, 20, 5,  9, 14, 20,
	4, 11, 16, 23, 4, 11, 16, 23, 4, 11, 16, 23, 4, 11, 16, 23,
	6, 10, 15, 21, 6, 10, 15, 21, 6, 10, 15, 21, 6, 10, 15, 21,
};

/* MD5 constants. Automatically generated by mksintab */
static const uint32_t md5const[64] =
#include "md5tab.h"

#define ROL(n, m) ((n) << (m) | (n) >> (32 - (m)))

extern void md5_block(union digest_state *u, const uint8_t *p) {
	struct md5_state *s = (struct md5_state*)u;

	int i, g;
	uint32_t a = s->h[0], b = s->h[1], c = s->h[2], d = s->h[3], f, t, x, y;
	const uint8_t *po;

	s->n++;

	for (i = 0; i < 64; i++) {
		if (i < 16) {
			f = b&c | ~b&d;
			g = i;
		} else if (i < 32) {
			f = d&b | ~d&c;
			g = 5*i + 1;
		} else if (i < 48) {
			f = b ^ c ^ d;
			g = 3*i + 5;
		} else {
			f = c ^ (b | ~d);
			g = 7*i;
		}

		t = d;
		d = c;
		c = b;
		/* compiler doesn't detect rotation when this is less explicit */
		po = p + sizeof(uint32_t)*(g&0xf);
		x = a + f + md5const[i];
		x += *po | *(po+1) << 8 | *(po+2) << 16 | *(po+3) << 24;
		y = shiftp[i];
		b += ROL(x, y);
		a = t;
	}

	s->h[0] += a;
	s->h[1] += b;
	s->h[2] += c;
	s->h[3] += d;
}

/* expects that n < 64. Overwrites p. */
extern void md5_final(union digest_state *u, uint8_t *p, size_t n, uint8_t *d) {
	finalize(u, p, n, d, MD5_DIGESTLEN, BIG, md5_block);
}
